### ISSUE TITLE
Death Loop with Potion Core

### ISSUE THREAD

**Issue by xAlicatt** [Insane-96/ProgressiveBosses#10]
I'm sure it's a conflict somewhere, but as my pack has over 250 mods, I'm not taking the time to test each individual mod to see where the conflict is. I don't have any error information or anything like that, cause there's no errors printed and no crashes caused...it just causes the deathstate of a player who has died to stay in perma-death. So upon respawning, you immediately are dead again. Teleporting somewhere else doesn't help. Creative mode/op doesn't help. The only thing that fixes it is deleting the playerdata.

This is the version of the pack that has this issue: https://minecraft.curseforge.com/projects/jakspack/files/2547306

**Comment by Insane-96** [comment]
I can't run the modpack so I can't test it. I don't have enough ram

But, I'm pretty sure it's not my mod that's causing this. I don't touch the player death / respawn or whatever.

**Comment by xAlicatt** [comment]
I dunno. I all I do know is that we have the issue with PB installed, and don't have the issue when it isn't. *shrug* I just wanted you to know.

**Comment by xAlicatt** [comment]
BTW, this happens in singleplayer as well as multiplayer (we don't use sponge, so it's not that either)

**Comment by Insane-96** [comment]
> I run it with 6gb.
sadly I have only 6gb so can't go over 5gb :/

**Comment by Insane-96** [comment]
Do you have potion core installed in the pack? Seems like is some kind of incompatibility with it.

**Comment by xAlicatt** [comment]
Yes. One of the mods we are running in my pack requires it.

**Comment by Insane-96** [comment]
It is then. The PotionCore causes it. just tested it.
I'll try to reach the dev and talk with him

**Comment by Insane-96** [comment]
Removing one of the mods will make the player be able to respawn properly again?

**Comment by xAlicatt** [comment]
Only after deleting player data in my experience...but I never attempted removing Potion Core obviously

**Comment by Insane-96** [comment]
Sadly I got no response from the Potion core guy.
I'll try again

**Comment by alfuken** [comment]
I confirm the death loop. Having only these two mods installed reproduces the bug.

**Comment by Insane-96** [comment]
I know, but I can't do anything
