### ISSUE TITLE
This seams to be breaking things.

### ISSUE THREAD

**Issue by CreeperBossVJ** [Insane-96/ProgressiveBosses#16]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.4.347.jar)
  ForgelinPlugin (Forgelin-1.7.4.jar)
  PlusTiC (plustic-5.2.1.3.jar)
  IceAndFireForgeLoading (iceandfire-1.0.1.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  MalisisCorePlugin (malisiscore-1.10.2-4.4.0.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  MicdoodlePlugin (MicdoodleCore-1.10.2-4.0.1.181.jar)
  BetterFoliageLoader (BetterFoliage-MC1.10.2-2.1.11.jar)
  AstralCore (astralsorcery-1.4.5.jar)
  MalisisSwitchesPlugin (malisisswitches-1.10.2-3.2.0.jar)
  MovingWorldCoreMod (movingworld-1.10.2-0007-full.jar)
  llibrary (llibrary-1.7.7-1.10.2.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.320-universal.jar)
  CTMCorePlugin (CTM-MC1.10.2-0.3.2.35.jar)
  OpenModsCorePlugin (OpenModsLib-1.10.2-0.11.5.jar)
  RebornCoreASM (RebornCore-1.10.2-2.13.6.142-universal.jar)
  IvToolkit (IvToolkit-1.3.3-1.10.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 9/19/18 11:41 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Progressive Bosses (progressivebosses)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/registries/IForgeRegistryEntry
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:65)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:594)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:559)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:220)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.registries.IForgeRegistryEntry
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 35 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1650006240 bytes (1573 MB) / 2083520512 bytes (1987 MB) up to 5965348864 bytes (5689 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6400m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2511 157 mods loaded, 157 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2511.jar) 
	UC	Forge{12.18.3.2511} [Minecraft Forge] (forge-1.10.2-12.18.3.2511.jar) 
	UC	ivtoolkit{1.3.3-1.10} [IvToolkit] (minecraft.jar) 
	UC	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UC	io.github.elytra.movingworld.common.asm.coremod{} [MovingWorld CORE] (minecraft.jar) 
	UC	openmodscore{0.11.5} [OpenModsLib Core] (minecraft.jar) 
	UC	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.9.320-universal.jar) 
	UC	JEI{3.14.8.422} [Just Enough Items] (jei_1.10.2-3.14.8.422.jar) 
	UC	appleskin{1.0.9} [AppleSkin] (AppleSkin-mc1.10.2-1.0.9.jar) 
	UC	csb_armorstand{1.0.4} [Armor Stand Configurator] (ArmorStandGUI-1.10-1.0.4.jar) 
	UC	astikoor{1.0.0} [Astikoor] (astikoor-1.0.0.jar) 
	UC	astralsorcery{1.4.5} [Astral Sorcery] (astralsorcery-1.4.5.jar) 
	UC	Psi{r1.0-42} [Psi] (Psi-r1.0-42.jar) 
	UC	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UC	badwithernocookiereloaded{1.10.2-2.12} [Bad Wither No Cookie! Reloaded] (badwithernocookiereloaded-1.10.2-2.12.jar) 
	UC	base{1.10.2-1.5.0} [B.A.S.E] (base-1.10.2-1.5.0.jar) 
	UC	Baubles{1.3.13} [Baubles] (Baubles-1.10.2-1.3.13.jar) 
	UC	bdlib{1.12.4.25} [BD Lib] (bdlib-1.12.4.25-mc1.10.2.jar) 
	UC	bedbugs{@VERSION@} [Bed Bugs] (BedBugs-1.10.2-1.1.6.jar) 
	UC	betterfoliage{2.1.11} [Better Foliage] (BetterFoliage-MC1.10.2-2.1.11.jar) 
	UC	betterthanbunnies{1.10.2-1.1.0} [BetterThanBunnies] (BetterThanBunnies-1.10.2-1.1.0.jar) 
	UC	BiblioCraft{2.2.5} [BiblioCraft] (BiblioCraft[v2.2.5][MC1.10.2].jar) 
	UC	openterraingenerator{v20} [Open Terrain Generator] (OpenTerrainGenerator-1.10.2-v21.jar) 
	UC	biomebundle{5.1} [Biome Bundle] (Biome_Bundle-1.10.2-v5.1.jar) 
	UC	bookshelf{1.4.4.347} [Bookshelf] (Bookshelf-1.10.2-1.4.4.347.jar) 
	UC	Botania{r1.9-341} [Botania] (Botania r1.9-341.jar) 
	UC	Chameleon{1.10.2-2.3.0} [Chameleon] (Chameleon-1.10.2-2.3.0.jar) 
	UC	chancecubes{1.10.2-3.1.1.221} [Chance Cubes] (ChanceCubes-1.10.2-3.1.1.221.jar) 
	UC	CodeChickenLib{2.5.9.320} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.9.320-universal.jar) 
	UC	CodeChickenCore{2.4.1.102} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.1.102-universal.jar) 
	UC	ChickenChunks{2.2.0.52} [ChickenChunks] (ChickenChunks-1.10.2-2.2.0.52-universal.jar) 
	UC	ctm{MC1.10.2-0.3.2.35} [CTM] (CTM-MC1.10.2-0.3.2.35.jar) 
	UC	chisel{MC1.10.2-0.2.1.46} [Chisel] (Chisel-MC1.10.2-0.2.1.46.jar) 
	UC	mcmultipart{1.4.0} [MCMultiPart] (MCMultiPart-1.4.0-universal.jar) 
	UC	chiselsandbits{12.18} [Chisels & Bits] (chiselsandbits-12.18.jar) 
	UC	shadowmc{3.6.1} [ShadowMC] (ShadowMC-1.10.2-3.6.1.jar) 
	UC	clipboard{@VERSION@} [Clipboard] (Clipboard-1.10.2-1.1.1.jar) 
	UC	clockhud{1.3.2} [Clock HUD] (ClockHUD-1.10.2-1.3.2.jar) 
	UC	clumps{1.0.5} [Clumps] (Clumps-1.0.5.jar) 
	UC	endercore{1.10.2-0.4.1.66-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.66-beta.jar) 
	UC	Waila{1.8.17-B31_1.10.2} [Waila] (Hwyla-1.8.17-B31_1.10.2.jar) 
	UC	EnderIO{1.10.2-3.1.193} [Ender IO] (EnderIO-1.10.2-3.1.193.jar) 
	UC	compatlayer{0.3.1} [compatlayer] (compatlayer-1.10-0.3.1.jar) 
	UC	cookingforblockheads{4.2.45} [Cooking for Blockheads] (CookingForBlockheads_1.10.2-4.2.45.jar) 
	UC	creeperconfetti{1.3} [Creeper Confetti] (creeperconfetti-1.2.1.jar) 
	UC	customizeddungeonloot{1.0.1} [§eCustomized Dungeon Loot] (Customized Dungeon Loot 1.10.2 (v.1.0.1).jar) 
	UC	custommainmenu{2.0.5} [Custom Main Menu] (CustomMainMenu-MC1.10.2-2.0.5.jar) 
	UC	darkutils{1.1.8.finalrc2} [Dark Utilities] (DarkUtilities-1.1.8.finalrc2.jar) 
	UC	movingworld{1.10.2-0007} [Moving World] (movingworld-1.10.2-0007-full.jar) 
	UC	davincisvessels{@DVESSELSVER@} [Davinci's Vessels] (davincisvessels-1.10.2-0006-full.jar) 
	UC	StorageDrawers{1.10.2-3.7.10} [Storage Drawers] (StorageDrawers-1.10.2-3.7.10.jar) 
	UC	bitdrawers{0.36} [Drawers & Bits] (DrawersBits-1.10.2-0.36.jar) 
	UC	forestry{5.2.17.390} [Forestry] (forestry_1.10.2-5.2.17.390.jar) 
	UC	eleccore{1.7.431} [ElecCore] (ElecCore-1.10.2-1.7.431.jar) 
	UC	csb_ench_table{1.1.3} [Lapis Stays in the Enchanting Table] (EnchantingTable-1.10-1.1.3.jar) 
	UC	enchdesc{1.0.0.0} [Enchantment Descriptions] (EnchantmentDescriptions-1.10.2-1.0.0.0.jar) 
	UC	EnderStorage{2.2.1.106} [EnderStorage] (EnderStorage-1.10.2-2.2.1.106-universal.jar) 
	UC	EnderZoo{1.10-1.2.3.44} [Ender Zoo] (EnderZoo-1.10-1.2.3.44.jar) 
	UC	galacticraftcore{4.0.1.181} [Galacticraft Core] (GalacticraftCore-1.10.2-4.0.1.181.jar) 
	UC	galacticraftplanets{4.0.1.181} [Galacticraft Planets] (Galacticraft-Planets-1.10.2-4.0.1.181.jar) 
	UC	mjrlegendslib{1.10.2-1.1.2} [MJRLegendsLib] (MJRLegendsLib-1.10.2-1.1.2.jar) 
	UC	extraplanets{1.10.2-1.1.5} [Extra Planets] (ExtraPlanets-1.10.2-1.1.5.jar) 
	UC	FastLeaveDecay{1.2.3} [Fast Leave Decay] (FastLeaveDecay-MC1.10.2-1.2.3.jar) 
	UC	flatcoloredblocks{mc1.10-v4.4} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.4.jar) 
	UC	forgelin{1.7.4} [Shadowfacts' Forgelin] (Forgelin-1.7.4.jar) 
	UC	forgemultipartcbe{2.0.0.38} [Forge Multipart CBE] (ForgeMultipart-1.10.2-2.0.0.38-universal.jar) 
	UC	microblockcbe{2.0.0.38} [Forge Microblocks] (ForgeMultipart-1.10.2-2.0.0.38-universal.jar) 
	UC	minecraftmultipartcbe{2.0.0.38} [Minecraft Multipart Plugin] (ForgeMultipart-1.10.2-2.0.0.38-universal.jar) 
	UC	fw{1.5.1} [Fullscreen Windowed] (FullscreenWindowed-1.10.2-1.5.1.jar) 
	UC	gendustry{1.6.5.32} [GenDustry] (gendustry-1.6.5.32-mc1.10.2.jar) 
	UC	googlyeyes{6.0.0} [GooglyEyes] (GooglyEyes-1.10.2-6.0.0.jar) 
	UC	ichunutil{6.5.0} [iChunUtil] (iChunUtil-1.10.2-6.5.0.jar) 
	UC	gravitygun{6.0.1} [GravityGun] (GravityGun-1.10.2-6.0.1.jar) 
	UC	headcrumbs{2.0.2} [Headcrumbs] (Headcrumbs-2.0.3.jar) 
	UC	llibrary{1.7.7} [LLibrary] (llibrary-1.7.7-1.10.2.jar) 
	UC	iceandfire{1.0.1} [Ice and Fire] (iceandfire-1.0.1.jar) 
	UC	immcraft{1.3.6} [Immersive Craft] (immcraft-1.1x-1.3.6.jar) 
	UC	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	UC	tconstruct{1.10.2-2.6.5.10} [Tinkers' Construct] (TConstruct-1.10.2-2.6.5.jar) 
	UC	immersiveengineering{0.10-61} [Immersive Engineering] (ImmersiveEngineering-0.10-61.jar) 
	UC	trackapi{1.1} [Track API] (TrackAPI-1.1_1.10.jar) 
	UC	immersiverailroading{1.3.3} [Immersive Railroading] (ImmersiveRailroading-1.3.3_1.10.jar) 
	UC	InfernalMobs{1.7.1} [Infernal Mobs] (InfernalMobs-1.10.jar) 
	UC	inventorytweaks{1.62-dev-66-c082db3} [Inventory Tweaks] (InventoryTweaks-1.62-dev-66.jar) 
	UC	jeibees{0.9.0.5} [JEI Bees] (jeibees-0.9.0.5-mc1.10.2.jar) 
	UC	journeymap{1.10.2-5.5.2} [JourneyMap] (journeymap-1.10.2-5.5.2.jar) 
	UC	jeresources{0.5.9.3} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.9.3.jar) 
	UC	kleeslabs{3.3.5} [KleeSlabs] (KleeSlabs_1.10.2-3.3.5.jar) 
	UC	laggoggles{FORGE-1.10.2-4.1} [LagGoggles] (LagGoggles-FORGE-1.10.2-4.1.jar) 
	UC	lycanitesmobs{1.17.1.2 - MC 1.10.2} [Lycanites Mobs] (LycanitesMobsComplete 1.17.1.2 [1.10.2].jar) 
	UC	arcticmobs{1.17.1.2 - MC 1.10.2} [Lycanites Arctic Mobs] (LycanitesMobsComplete 1.17.1.2 [1.10.2].jar) 
	UC	demonmobs{1.17.1.2 - MC 1.10.2} [Lycanites Demon Mobs] (LycanitesMobsComplete 1.17.1.2 [1.10.2].jar) 
	UC	desertmobs{1.17.1.2 - MC 1.10.2} [Lycanites Desert Mobs] (LycanitesMobsComplete 1.17.1.2 [1.10.2].jar) 
	UC	forestmobs{1.17.1.2 - MC 1.10.2} [Lycanites Forest Mobs] (LycanitesMobsComplete 1.17.1.2 [1.10.2].jar) 
	UC	freshwatermobs{1.17.1.2 - MC 1.10.2} [Lycanites Freshwater Mobs] (LycanitesMobsComplete 1.17.1.2 [1.10.2].jar) 
	UC	infernomobs{1.17.1.2 - MC 1.10.2} [Lycanites Inferno Mobs] (LycanitesMobsComplete 1.17.1.2 [1.10.2].jar) 
	UC	junglemobs{1.17.1.2 - MC 1.10.2} [Lycanites Jungle Mobs] (LycanitesMobsComplete 1.17.1.2 [1.10.2].jar) 
	UC	mountainmobs{1.17.1.2 - MC 1.10.2} [Lycanites Mountain Mobs] (LycanitesMobsComplete 1.17.1.2 [1.10.2].jar) 
	UC	plainsmobs{1.17.1.2 - MC 1.10.2} [Lycanites Plains Mobs] (LycanitesMobsComplete 1.17.1.2 [1.10.2].jar) 
	UC	saltwatermobs{1.17.1.2 - MC 1.10.2} [Lycanites Saltwater Mobs] (LycanitesMobsComplete 1.17.1.2 [1.10.2].jar) 
	UC	shadowmobs{1.17.1.2 - MC 1.10.2} [Lycanites Shadow Mobs] (LycanitesMobsComplete 1.17.1.2 [1.10.2].jar) 
	UC	swampmobs{1.17.1.2 - MC 1.10.2} [Lycanites Swamp Mobs] (LycanitesMobsComplete 1.17.1.2 [1.10.2].jar) 
	UC	magicbees{1.0} [MagicBees] (MagicBees-Beta-3.0.4.jar) 
	UC	malisiscore{1.10.2-4.4.0} [MalisisCore] (malisiscore-1.10.2-4.4.0.jar) 
	UC	malisisdoors{1.10.2-5.2.0} [MalisisDoors] (malisisdoors-1.10.2-5.2.0.jar) 
	UC	malisisswitches{1.10.2-3.2.0} [Malisis Switches] (malisisswitches-1.10.2-3.2.0.jar) 
	UC	minecolonies{@VERSION@} [MineColonies] (minecolonies-universal-1.10.2-0.9.7587.jar) 
	UC	minetogether{unspecified} [MineTogether] (minetogether-1.10.2-2.1.3.jar) 
	UC	minetogetherserver{unspecified} [MineTogetherServer] (minetogether-1.10.2-2.1.3.jar) 
	UC	testdummy{1.11} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.10.2-1.13.jar) 
	UC	mobamputation{6.0.0} [MobAmputation] (MobAmputation-1.10.2-6.0.0.jar) 
	UC	ModNameTooltip{1.6.0} [Mod Name Tooltip] (modnametooltip_1.10.2-1.6.0.jar) 
	UC	moreoverlays{1.11} [MoreOverlays] (moreoverlays-1.11-mc1.10.2.jar) 
	UC	Morpheus{1.10.2-3.1.13} [Morpheus] (Morpheus-1.10.2-3.1.13.jar) 
	UC	naturescompass{1.3.1} [Nature's Compass] (NaturesCompass-1.10.2-1.3.1.jar) 
	UC	netherportalfix{1.0} [NetherPortalFix] (NetherPortalFix_1.10.2-3.3.7.jar) 
	UC	nmsot{1.2.0-mc1.10.2} [No Mob Spawning on Trees] (NoMobSpawningOnTrees-1.2.0-mc1.10.2.jar) 
	UC	openmods{0.11.5} [OpenModsLib] (OpenModsLib-1.10.2-0.11.5.jar) 
	UC	openblocks{1.7.6} [OpenBlocks] (OpenBlocks-1.10.2-1.7.6.jar) 
	UC	harvestcraft{1.10.2j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.10.2j.jar) 
	UC	pamscookables{1.0} [Pam's Cookables] (pamscookables-1.10.2_1.0.0.jar) 
	UC	plustic{5.2.1.3} [PlusTiC] (plustic-5.2.1.3.jar) 
	UE	progressivebosses{1.3.1} [Progressive Bosses] (ProgressiveBosses-1.3.1-mc1.10.x.jar) 
	UC	reborncore{2.13.6.142} [RebornCore] (RebornCore-1.10.2-2.13.6.142-universal.jar) 
	UC	quantumstorage{3.3.6} [QuantumStorage] (QuantumStorage-1.10.2-3.3.6.jar) 
	UC	rangedpumps{0.3} [Ranged Pumps] (rangedpumps-0.3.jar) 
	UC	RealisticTorches{1.6.4} [Realistic Torches] (RealisticTorches-1.10.2-1.6.4.jar) 
	UC	reauth{3.5.2} [ReAuth] (ReAuth-3.5.2.jar) 
	UC	reborncore-mcmultipart{2.13.6.142} [reborncore-MCMultiPart] (RebornCore-1.10.2-2.13.6.142-universal.jar) 
	UC	refinedstorage{1.2.26} [Refined Storage] (refinedstorage-1.2.26.jar) 
	UC	rebornstorage{1.0.0} [RebornStorage] (RebornStorage-1.10.2-1.0.3.30.jar) 
	UC	reccomplex{1.4.5-1.10} [Recurrent Complex] (RecurrentComplex-1.4.5-1.10.jar) 
	UC	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.9.4-1.7.4.jar) 
	UC	reptilemod{3.5.2} [Reptile Mod] (reptilemod-1.10.2-3.5.2-58.jar) 
	UC	roguelike{1.5.9} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.9.jar) 
	UC	secretroomsmod{5.1.9} [Secret Rooms 5] (secretroomsmod-1.10.2-5.1.9.jar) 
	UC	SimpleLabels{0.0.1} [SimpleLabels] (simplelabels-1-10.2-0.0.3.jar) 
	UC	SleepingBag{1.4.0} [Sleeping Bag] (SleepingBag-1.10.2-1.4.0.jar) 
	UC	stg{1.10.2-1.0.3} [SwingThroughGrass] (stg-1.10.2-1.0.3.jar) 
	UC	storagedrawersextra{1.10-1.1.0} [Storage Drawers Extras] (StorageDrawersExtras-1.10-1.1.0.jar) 
	UC	rscircuits{1.0.4} [Super Circuit Maker] (SuperCircuitMaker-1.0.4.jar) 
	UC	supersoundmuffler{1.0.1.4} [Super Sound Muffler] (supersoundmuffler-1.10.2-1.0.1.4.jar) 
	UC	thaumcraft{6.0.BETA8} [Thaumcraft] (Thaumcraft-1.10.2-6.0.BETA8.jar) 
	UC	tcinventoryscan{2.0.7} [Thaumcrafft Inventory Scanning] (ThaumcraftInventoryScanning_1.10.2-2.0.7.jar) 
	UC	ThaumicJEI{1.1.2} [ThaumicJEI] (ThaumicJEI-1.10.2-1.1.3-2.jar) 
	UC	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
	UC	tipthescales{1.0.1} [TipTheScales] (TipTheScales-1.10.2-1.0.1.jar) 
	UC	torchmaster{1.4.1.34} [TorchMaster] (torchmaster_1.10.2-1.4.1.34.jar) 
	UC	Translocator{2.1.4.55} [Translocator] (Translocators-1.10.2-2.1.4.55-universal.jar) 
	UC	waddles{0.5.4} [Waddles] (Waddles-1.10.2-0.5.4.jar) 
	UC	WailaHarvestability{1.1.10} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.10.jar) 
	UC	wanionlib{1.10.2-1.3} [WanionLib] (WanionLib-1.10.2-1.3.jar) 
	UC	wrcbe{2.0.0} [WirelessRedstone-CBE] (WR-CBE-1.10.2-2.0.0.18-universal.jar) 
	UC	yoyos{1.10.2-0.2.0-5-} [Yoyos] (yoyos-1.10.2-0.2.0-5-.jar) 
	UC	denseores{1.0} [denseores] (denseores-1.11-1.0.2.jar) 
	UC	unidict{1.10.2-2.9b} [UniDict] (UniDict-1.10.2-2.9b.jar) 
	Loaded coremods (and transformers): 
BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.4.347.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
ForgelinPlugin (Forgelin-1.7.4.jar)
  
PlusTiC (plustic-5.2.1.3.jar)
  landmaster.plustic.asm.Transform
IceAndFireForgeLoading (iceandfire-1.0.1.jar)
  com.github.alexthe666.iceandfire.access.IceAndFireTransformer
FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  invtweaks.forge.asm.ContainerTransformer
MalisisCorePlugin (malisiscore-1.10.2-4.4.0.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
MicdoodlePlugin (MicdoodleCore-1.10.2-4.0.1.181.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
BetterFoliageLoader (BetterFoliage-MC1.10.2-2.1.11.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
AstralCore (astralsorcery-1.4.5.jar)
  
MalisisSwitchesPlugin (malisisswitches-1.10.2-3.2.0.jar)
  net.malisis.switches.asm.MalisisSwitchesTransformer
MovingWorldCoreMod (movingworld-1.10.2-0007-full.jar)
  
llibrary (llibrary-1.7.7-1.10.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.320-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
CTMCorePlugin (CTM-MC1.10.2-0.3.2.35.jar)
  team.chisel.ctm.client.asm.CTMTransformer
OpenModsCorePlugin (OpenModsLib-1.10.2-0.11.5.jar)
  openmods.core.OpenModsClassTransformer
RebornCoreASM (RebornCore-1.10.2-2.13.6.142-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
IvToolkit (IvToolkit-1.3.3-1.10.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 399.07' Renderer: 'GeForce GTX 1070/PCIe/SSE2'
	OpenModsLib class transformers: [pre_world_render_hook:FINISHED],[movement_callback:FINISHED],[player_damage_hook:FINISHED],[map_gen_fix:ENABLED],[player_render_hook:ENABLED],[horse_null_fix:FINISHED]
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

**Comment by Insane-96** [comment]
Sorry, porting the mod to 1.10 was a huge mistake. Going to remove the version on curseforge. 1.10 is no longer supported and that speedy port that I did made the mod not working for 1.10

**Comment by WailordUBS** [comment]
@Insane-96 Are higher versions supported?
